### ISSUE TITLE
Does it support react hooks?

### ISSUE THREAD

**Issue by jonit-dev** [amarofashion/react-credit-cards#83]
Hey guys, 

I'm getting the following error while trying to integrate this package on my code:

```
React.createClass is not a function
TypeError: React.createClass is not a function
    at Object.<anonymous> (/usr/src/app/node_modules/react-credit-card/build/card.js:13:26)
    at Object.<anonymous> (/usr/src/app/node_modules/react-credit-card/build/card.js:199:4)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.react-credit-card (/usr/src/app/.next/server/static/development/pages/payment.js:7647:18)
    at __webpack_require__ (/usr/src/app/.next/server/static/development/pages/payment.js:23:31)
    at Module../src/components/pages/payment/CreditCardPayment.tsx (/usr/src/app/.next/server/static/development/pages/payment.js:3967:75)
    at __webpack_require__ (/usr/src/app/.next/server/static/development/pages/payment.js:23:31)
    at Module../src/pages/payment.tsx (/usr/src/app/.next/server/static/development/pages/payment.js:6207:102)
    at __webpack_require__ (/usr/src/app/.next/server/static/development/pages/payment.js:23:31)
    at Object.4 (/usr/src/app/.next/server/static/development/pages/payment.js:7283:18)

```

Code: 
```
import { TextField } from '@material-ui/core';
import React, { useState } from 'react';
import Cards from 'react-credit-card';
import styled from 'styled-components';

export const CreditCardPayment: React.FC = (props) => {
  const [creditCard, setCreditCard] = useState({
    cvc: "",
    expiry: "",
    focus: "",
    name: "",
    number: "",
  });

  const handleInputFocus = (e) => {
    setCreditCard({ ...creditCard, focus: e.target.name });
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setCreditCard({
      ...creditCard,
      [name]: value,
    });
  };

  return (
    <Container>
      <Cards
        cvc={creditCard.cvc}
        expiry={creditCard.expiry}
        focused={creditCard.focus}
        name={creditCard.name}
        number={creditCard.number}
      />
      <form autoComplete="off">
        <TextField
          name="name"
          label="Nome"
          type="text"
          value={creditCard.name}
          onFocus={handleInputFocus}
          onChange={handleInputChange}
        />
      </form>
    </Container>
  );
};

const Container = styled.div``;

```

**Comment by jonit-dev** [comment]
Nevermind, I guess I just installed the wrong dependency (react-credit-card) instead of react-credit-card

**Comment by ramadi12** [comment]
Lo estaba intentando y me da error
